require 'aws-sdk'
require 'getoptlong'

def help
    puts <<-EOF
Usage: ruby s3.rb [OPTION]=[VALUE] ...

DESCRIPTION

    Generate presigned URLs for S3 resources, specifying their expiry time in seconds (maximum 1 week).

OPTIONS

    --aws-profile, -i
            This is the name of the IAM role listed in the shared credentials file (~/.aws/credentials).

    --aws-region, -r
            The AWS region where the S3 bucket and key exist.

    --s3-bucket, -b
            The name of the S3 bucket.

    --s3-key, -k
            The name of the resource to be downloaded using the presigned URL generated by this script.

    --expiry-time, -t
            Number of seconds after which the presigned URL will be invalid.

    --help, -h
            Print this help message

AUTHOR / CONTRIBUTORS
    synbit

SOURCE
    https://github.com/synbit/aws
EOF
end

opts = GetoptLong.new(
    ['--aws-profile', '-i', GetoptLong::REQUIRED_ARGUMENT],
    ['--aws-region', '-r', GetoptLong::REQUIRED_ARGUMENT],
    ['--s3-bucket', '-b', GetoptLong::REQUIRED_ARGUMENT],
    ['--s3-key', '-k', GetoptLong::REQUIRED_ARGUMENT],
    ['--expiry-time', '-t', GetoptLong::REQUIRED_ARGUMENT],
    [ '--help', '-h', GetoptLong::NO_ARGUMENT ]
)

aws_profile, aws_region, s3_bucket, s3_key, expiry_time = nil

opts.each do |opt, arg|
    case opt
    when '--help', '-h'
        help()
    when '--aws-profile', '-i'
        aws_profile = arg
    when '--aws-region', '-r'
        aws_region = arg
    when '--s3-bucket', '-b'
        s3_bucket = arg
    when '--s3-key', '-k'
        s3_key = arg
    when '--expiry-time', '-t'
        expiry_time = arg.to_i
    end
end

if (aws_profile.nil? or aws_region.nil? or s3_bucket.nil? or s3_key.nil? or expiry_time.nil?)
    abort(help())
end

profile = Aws::SharedCredentials.new(
    profile_name: aws_profile,
    region: aws_region
)

s3 = Aws::S3::Client.new(
    region: aws_region,
    credentials: profile.credentials
)

s3_presigner = Aws::S3::Presigner.new(
    client: s3
)

url = s3_presigner.presigned_url(
    :get_object,
    params = {
        bucket: s3_bucket,
        key: s3_key,
        expires_in: expiry_time
    }
)

puts("Enyone with the following link will be able to download the resources specified:")
puts("S3 bucket: '#{s3_bucket}',\nS3 key: #{s3_key},\nExpires in: #{expiry_time} seconds,\nURL: #{url}")
